# Generated by Django 3.2.15 on 2022-09-07 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 8, 20, 23, 646686, tzinfo=utc), verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
